global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:8080' ]

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'auth-service:9002' ]

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'user-service:9003' ]

  - job_name: 'data-analysis-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'data-analysis-service:9000' ]

  - job_name: 'data-retrieval-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'data-retrieval-service:9004' ]

  - job_name: 'discovery-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'discovery-server:8001' ]

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'config-server:8081' ]
