global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081', 'data-retrieval-service:9004', 'auth-service:9002', 'data-analysis-service:9000', 'api-gateway:8080']
