[SERVICE]
    Flush                     1
    Log_Level                 info
    Parsers_File              /fluent-bit/etc/parsers.conf
    storage.path              /tmp/fluent-bit
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 50M

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*-json.log
    Parser            docker
    Tag               docker.*
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    Refresh_Interval  10
    DB                /tmp/fluent-bit/docker-containers.db

[FILTER]
    Name                modify
    Match               docker.*
    Add                 source docker

[OUTPUT]
    Name            tcp
    Match           docker.*
    Host            logstash
    Port            5044
    Format          json_lines
    Retry_Limit     False
